### ISSUE TITLE
Plugin fails to connect with forward-slash on the end of the instance URL

### ISSUE THREAD

**Issue by ars3nic** [mdziekon/octoprint-spoolman#31]
### The problem

When providing the Spoolman instance URL to the plugin, if a forward slash ('/') is included at the end of the URL, the plugin fails to connect to the instance and returns "Unknown error".  Removing the slash results in a successful connection to Spoolman.

![2024-04-28 09_23_01-OctoPrint](https://github.com/mdziekon/octoprint-spoolman/assets/14172512/8e8f0d42-211b-4a8b-9f69-194ab8da8b71)
![2024-04-28 09_23_08-OctoPrint](https://github.com/mdziekon/octoprint-spoolman/assets/14172512/c1503057-0ff7-49a2-8ee9-49d31451fccc)

I discovered this issue when I copied my Spoolman URL from the Chrome address bar to paste it into the plugin, and Chrome automatically appended the slash after the port number.  So it's not a big deal, but given Chrome's popularity and the likelihood that other people will encounter this, either providing a notice to the user or automatically ignoring/dropping the slash would be helpful.

### Version of octoprint-spoolman

1.0.1

### Version of OctoPrint

1.10.0

### Operating system running OctoPrint

OctoPi 1.0.0

### Browser and version of browser, operating system running browser

Chrome 124.0.6367.63, Windows 10

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20240428092805.zip](https://github.com/mdziekon/octoprint-spoolman/files/15142459/octoprint-systeminfo-20240428092805.zip)

**Comment by mdziekon** [comment]
Hi @ars3nic, thanks for the bringing my attention to this problem.

Ignoring the trailing slash sounds indeed like a good idea, as this might be a common issue. Will put this on my backlog.

**Comment by mdziekon** [comment]
Fix has been merged into master, and I'll try to push a release candidate as well.
