### ISSUE TITLE
[Request] Lot no or some other identifier in UI

### ISSUE THREAD

**Issue by rishi4999** [mdziekon/octoprint-spoolman#52]
### Is your feature request related to a problem? Please describe.

Have multiple spools of same color from same manufacturer but no idenfier availiable for spool on octoprint

### Describe the solution you'd like

SOme identifer like Lot No visible on the UI to better identify spool being used

### Describe alternatives you've considered

I check remaining weight on the spools and match using spoolman UI to see which lot no has now much remaininig

**Comment by crzykidd** [comment]
I would love to see spool ID as that is how I number all my spools, so seeing that in the pick list would be great.

**Comment by mdziekon** [comment]
> I would love to see spool ID as that is how I number all my spools, so seeing that in the pick list would be great.

@crzykidd the Spool ID (as returned by Spoolman) is already being displayed in the spools picker list. Am I missing something, or did you mean to also include that attribute in the sidebar display?

**Comment by mdziekon** [comment]
Thanks to @jameswolff96 contribution, the Lot # is now being displayed in the Spool picker modal. Sidebar modifications have been discussed as well, but will be introduced in a separate PR.
